version: "3"
services:
  db:
    image: seidakhmet/postgres:cube512
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}"
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      PGDATA: "${PGDATA}"
    ports:
      - "5432:5432"
    volumes:
      - "${PGDATA_VOLUME}"
